version: "3.8"

services:
  postgresql:
    image: postgres
    container_name: pg-docker
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - $HOME/Desktop/PostgreSql-Snippets/infile:/infile
      - ./db:/docker-entrypoint-initdb.d/
    restart: always
